import { Providers } from "./providers";
import { fonts } from "./fonts";
import { Inter } from "next/font/google";
import "./globals.css";
import "./index.css";
import Head from "next/head";
import Link from "next/link";
import "./layout.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={"app " + inter.className}>
        <Providers>
          <div className="main-layout">
            <div className="main-layout__header">
              <header className="text-white py-4">
                <div className="flex justify-between items-center pl-3">
                  <Link href="/" legacyBehavior>
                    <a className="text-xl font-bold">SafeShortner</a>
                  </Link>
                </div>
              </header>
            </div>
            <main className="main-layout__container">
              <div className="content-width mx-auto">{children}</div>
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
